### ISSUE TITLE
Menu nesting working incorrectly for Jekyll

### ISSUE THREAD

**Issue by ncphillips** [forestryio/jekyll-menus#13]
@chrisdmacrae commented on [Sat Sep 30 2017](https://github.com/forestryio/admin/issues/826)

## Current Behaviour

Menu nesting is broken for Jekyll. It works like Hugo, setting the "parent" parameter of the menu item.

```
menus:
    parent_menu_id:
        parent: parent_menu_item_id
        weight: 1
```

However, in Jekyll menus this is done by treating the "parent" as a whole new menu, like so:

```
menus:
    parent_menu_item_id:
      weight: 1
```

## Steps to reproduce

1.

## Environment
 

---

@chrisdmacrae commented on [Tue Oct 10 2017](https://github.com/forestryio/admin/issues/826#issuecomment-335477827)

This can likely be fixed in the Jekyll Menus plugin, instead of in Forestry.
