### ISSUE TITLE
Menu Items do not contain children to generate sub menus

### ISSUE THREAD

**Issue by andrewmkrug** [forestryio/jekyll-menus#14]
I have tried doing it with the `parent` being set in the menu items and by directly creating a `children` in the YAML file.

I have debugged it as well and the `Jekyll:: Menus::Drops::Item` doesn't contain anything in either case. 

What is the proper way to generate sub menus that are only external links?

**Comment by envygeeks** [comment]
How are you doing it now? Please provide examples of your current usage.

**Comment by andrewmkrug** [comment]
menus.yaml

```yaml
---
header:
- identifier:
  url: http://2017.seleniumconf.us
  weight: 2
  parent: confs
  title: Austin 2017
- identifier: confs
  url: "/"
  weight: 2
  title: Past Conferences
```

and i have tried 

```yaml
---
header:
- identifier: confs
  url: "/"
  weight: 2
  title: Past Conferences
  children:
  - identifier:
    url: http://2017.seleniumconf.us
    weight: 2
    parent: confs
    title: Austin 2017
```

neither way allows me to loop thru the `item.children`

**Comment by andrewmkrug** [comment]
@envygeeks bump

**Comment by envygeeks** [comment]
hey, sorry about forgetting about this.  I'll try to replicate this in the morning and get back to you!

**Comment by sethcarlton** [comment]
I am running into an issue here as well. Let's say I have an About menu item in the header and I want a submenu item called Team. According to the jekyll-menus documentation I would accomplish that like so:

```
# in about.md
menus:
  header:
    name: About
    identifier: about
    weight: 0

# in team.md
menus: about
```

If I do it this way, children are included with the menu items in `site.menus.header`

However, when adding **internal** menu items via **Forestry**, the resulting format is as follows:
```
# in about.md
menu:
  header:
    name: About
    identifier: about
    weight: 0

# in team.md
menu:
  header:
    name: Team
    identifier: team
    weight: 0
    parent: about
```

The children items are no longer included with the item in `site.menus.header`
