### ISSUE TITLE
Would love some examples

### ISSUE THREAD

**Issue by todrobbins** [forestryio/jekyll-menus#7]
I'm trying to get a simple two-level menu working in my header and having a hard time.

```
- Home
- Projects
  - Project 1
  - Project 2
- About
```

**Comment by todrobbins** [comment]
My `menus.yml`:

```
main:
  - title: Main
  - identifier: main
  - url: /

projects:
  - title: Projects
  - identifier: projects
  - url: /projects/
```

And my `header.html` include:

```
<nav>
  {% for my_page in site.menus.projects %}
    {% if my_page.title %}
      <a class="page-link" href="{{ my_page.url | relative_url }}">{{ my_page.title | escape }}</a>
    {% endif %}
  {% endfor %}
</nav>
```

I know I'm probably missing something obvious. 😁

**Comment by envygeeks** [comment]
Hi @todrobbins,

You can see format examples here: https://github.com/forestryio/jekyll-menus#examples-1
That should be

```yaml
main:
  - title: Projects
    identifier: projects
    url: /projects

  - title: Home
    identifier: Home
    url: /
projects:
  - title: Project1
    url: /projects/project1
    identifier: project1
```
